package com.smartwealth.smartwealth_backend.entity.enums;

public enum FailureReasonType {
    BUSINESS_LOGIC,
    WALLET_TRANSACTION_FAILURE,
    INVALID_REQUEST,
    UNKNOWN,
    TRANSACTION_FAILURE,
    ILLEGAL_STATE,
    HOLDING_NOT_FOUND,
    HOLDING_UPDATE_FAILED,
    INVALID_SELL_REQUEST,
    PLAN_NOT_FOUND, INVALID_INVESTMENT_ORDER, TRANSACTION_NOT_FOUND, TEMPORARY_SYSTEM_ISSUE
}

