-- V1__create_sequence_and_users_table.sql
-- Flyway migration: create sequence and users table for SmartWealth

-- 1) Sequence for customer_id
CREATE SEQUENCE IF NOT EXISTS customer_id_seq
  START WITH 10000000
  INCREMENT BY 1
  MINVALUE 10000000
  NO MAXVALUE
  CACHE 1;

-- 2) Users table
CREATE TABLE IF NOT EXISTS users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   VARCHAR(8),
    email         VARCHAR(100) NOT NULL,
    mobile_number VARCHAR(10)  NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(100) NOT NULL,
    role          VARCHAR(255) NOT NULL DEFAULT 'USER',
    kyc_status    VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    risk_profile  VARCHAR(255) NOT NULL DEFAULT 'MODERATE',
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP    NOT NULL DEFAULT now(),
    last_login_at TIMESTAMP
    );

-- 3) Unique constraints
ALTER TABLE users ADD CONSTRAINT uc_users_customer UNIQUE (customer_id);
ALTER TABLE users ADD CONSTRAINT uc_users_email UNIQUE (email);
ALTER TABLE users ADD CONSTRAINT uc_users_mobile_number UNIQUE (mobile_number);

-- 4) Indexes for fast lookup (customer_id, email, mobile)
CREATE INDEX IF NOT EXISTS idx_user_customer_id ON users (customer_id);
CREATE INDEX IF NOT EXISTS idx_user_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_user_mobile_number ON users (mobile_number);
