-- V1__create_sequence_and_users_table.sql
-- Flyway migration: create sequence and users table for SmartWealth

-- 1) Sequence for customer_id

DROP SEQUENCE IF EXISTS customer_id_seq;

CREATE SEQUENCE customer_id_seq
    START WITH 10000000
    INCREMENT BY 1
    MINVALUE 10000000
    NO MAXVALUE
    CACHE 1;

DROP TABLE IF EXISTS users CASCADE;

-- 2) Users table
CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   VARCHAR(8)   NOT NULL UNIQUE,
    email         VARCHAR(100) NOT NULL UNIQUE,
    mobile_number VARCHAR(10)  NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(100) NOT NULL,
    date_of_birth DATE         NOT NULL,
    gender        VARCHAR(20)  NOT NULL,
    address_line_1 VARCHAR(255) NOT NULL,
    address_line_2 VARCHAR(255),
    city           VARCHAR(100) NOT NULL,
    state          VARCHAR(100) NOT NULL,
    country        VARCHAR(100) NOT NULL,
    postal_code    VARCHAR(20) NOT NULL,
    role          VARCHAR(20) NOT NULL DEFAULT 'USER',
    kyc_status    VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    risk_profile  VARCHAR(20) NOT NULL DEFAULT 'MODERATE',
    is_active     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login_at TIMESTAMPTZ
);

-- 4) Indexes for fast lookup (kyc_status and is_active)
CREATE INDEX IF NOT EXISTS idx_user_kyc_active ON users (kyc_status, is_active);